### ISSUE TITLE
Kunnen we checkbox "add to favorite" in public.html naar links vast houden aub?

### ISSUE THREAD

**Issue by hanifa1** [Orhon/FlexiDating#1]

**Comment by AdmiralOfTheFleet** [comment]
Even geduld Hanifa, dank voor het te melden. Gelieve geen layout-aanpassingen te doen a.u.b.

**Comment by hanifa1** [comment]
Hey, ik gewoon laat je weten :) Ik zou niks meer in public.html en index.html aanpassen (in index.html ook een probleempje met scrumlib:). Ik ga nu in toonFavoritten.html werken om favoritten te tonen en in favoritten.js om favoritten te verdwijnen

**Comment by AdmiralOfTheFleet** [comment]
Geen probleem Hanifa,
dank om het te melden van de checkbox. Zal ervoor kijken, ga straks en zaterdag pagina per pagina de layout bekijken. 
Dus even geduld dat alles niet correct staat qua layout. 
Het is heel lief dat je dat direct wil zien aangepast, maar het help niet met zelf wijzigingen aan te brengen, want dan zoek ik naar bepaalde fout niet wetende van waar die komt. 
Groetjes,
Brecht
